### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Timaces** [diegovalsesia/GraphCNN-GAN-codeonly#1]
thank you for your work!

when I run the main.py，meeting the question：
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    all_pc_data = load_all_point_clouds_under_folder(class_dir, n_threads=8, file_ending='.ply', verbose=True)
  File "/home/l/Desktop/GraphCNN-GAN-codeonly-master/gconv_up_aggr_code/in_out.py", line 115, in load_all_point_clouds_under_folder
    pclouds, model_ids, syn_ids = load_point_clouds_from_filenames(file_names, n_threads, loader=pc_loader, verbose=verbose)
  File "/home/l/Desktop/GraphCNN-GAN-codeonly-master/gconv_up_aggr_code/in_out.py", line 120, in load_point_clouds_from_filenames
    pc = loader(file_names[0])[0]
IndexError: list index out of range

thank you very much

**Comment by Ayushithakre12** [comment]
Always keep in mind when you want to overcome this error, the default value of indexing and range starts from 0, so if total items is 100 then l[99] and range(99) will give you access up to the last element.

whenever you get this type of error please cross check with items that comes between/middle in range, and insure that their index is not last if you get output then you have made perfect error that mentioned above.
